trigger:
  - main

pool:
  vmImage: "windows-latest"

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: "12.x"
    displayName: "Install Node.js"

  - script: npm install
    displayName: "Install dependencies"

  - script: npm run build
    displayName: "Build project"

  - task: AzureRmWebAppDeployment@4
    displayName: "Deploy to Stage Slot"
    inputs:
      ConnectionType: 'AzureRM'
      azureSubscription: 'Mi primera subscripcion de Azure(1)(238ca010-f875-4ebe-b5d0-1006ab33e7b9)'
      appType: 'webApp'
      WebAppName: 'recieptmanagerApp'
      packageForLinux:  '$(System.DefaultWorkingDirectory)/**/*.war'
      AppSettings: '-ASPNETCORE_ENVIRONMENT Development'
